; PlatformIO Project Configuration File

[env:hf-amoled]
platform = espressif32@6.10.0
platform_packages = toolchain-xtensa-esp32s3 @ ~11.2.0
; framework = espidf
framework = arduino
board = esp32-s3-devkitc-1

# 串口设置
monitor_speed = 115200
upload_speed = 460800
monitor_filters = direct
upload_protocol = esptool

# 重置方法
upload_resetmethod = usb_reset

# 额外的上传参数
upload_flags = 
    --before=default_reset
    --after=hard_reset
    --chip=esp32s3
    --no-stub    # 添加这个参数可能会提高上传稳定性

# 指定串口
monitor_port = /dev/cu.usbmodem*
upload_port = /dev/cu.usbmodem*

build_type = release

board_build.flash_size = 8MB
build_unflags = -std=gnu++11
build_flags = 
    -std=gnu++17      ; C++代码用 C++17
    -DCONFIG_ARDUINO_CXX_STD=17
    -std=gnu11        ; C代码用 C11（重要！！）
    -DCONFIG_FREERTOS_HZ=1000
    -DCONFIG_LV_USE_LOG=0
    -DUSE_SCREEN_BACKLIGHT_CONTROL
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I.
    -I include
    -I lib
    -Wno-error=unused-function
    -DARDUINO_USB_DFU_ON_BOOT=0
build_flags_c = -std=gnu11
build_flags_cpp = -std=gnu++17
# 添加本地库搜索路径    
lib_extra_dirs = ${PROJECT_DIR}/lib

lib_ldf_mode = deep+

lib_deps = 
    ArduinoJson
    NTPClient
    ; 基础底层功能
    ; https://github.com/esp-arduino-libs/esp-lib-utils.git
    ; https://github.com/esp-arduino-libs/ESP32_IO_Expander.git # 0.0.3

    ; 显示相关 (图形界面 / 驱动库)
    ; https://github.com/lvgl/lvgl.git # v8.4.0
    ; https://github.com/moononournation/Arduino_GFX.git # 1.4.9

    ; 触摸屏相关
    ; https://github.com/Xk-w/Arduino_DriveBus.git # 1.0.1

    ; 电源管理相关
    https://github.com/lewisxhe/XPowersLib.git # 0.2.6

    ; 传感器相关
    https://github.com/lewisxhe/SensorLib.git # 0.2.3
board_build.partitions = partitions.csv